### PR TITLE
Use service account token function from thoth-common

### PR DESCRIPTION
**Pull request by fridex**
Depends-On: https://github.com/thoth-station/common/pull/32

### CODE REVIEW

**Comment by goern** [comment]
see https://docs.openstack.org/infra/zuul/user/gating.html#cross-project-dependencies

**Comment by fridex** [comment]
> see https://docs.openstack.org/infra/zuul/user/gating.html#cross-project-dependencies

Thanks, I see you've already updated it. :smile:

**Review by goern — APPROVED** [review]
/approve

**Comment by fridex** [comment]
Hehe, we should have zuul for this repo :angel: - this shouldn't pass tests as we are importing function that is not present in the currently pinned thoth-common release.

**Pull request merged**
