### PR TITLE
port to python 38

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545

### CODE REVIEW

**Comment by harshad16** [comment]
please check this comment: https://github.com/thoth-station/amun-api/pull/590#issuecomment-732707776

**Comment by bissenbay** [comment]
> please check this comment: [thoth-station/amun-api#590 (comment)](https://github.com/thoth-station/amun-api/pull/590#issuecomment-732707776)

thanks a lot, @harshad16

**Review by fridex — APPROVED** [review]
:smile_cat:

**Pull request merged**
